server:
  port: 6666
management:
  endpoints:
    web:
      #base-path: "/actuator"
      exposure:
        include: "*"
spring:
  application:
    name: gt
  cloud:
    zookeeper:
      connect-string: 172.16.8.52:2181
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true