server:
  port: 7777
spring:
  application:
    name: my-gateway
  cloud:
    gateway:
      routes:
        - id: user-center-test
          uri: http://127.0.0.1:7690
          predicates:
          - Path=/**